[package]
name = "minimal-fixtures"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]

[dependencies]
minimal-fixtures-macros = { path = "minimal-fixtures-macros", version = "0.1.0" }
