[package]
name = "minimal-fixtures-macros"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]

[lib]
proc-macro = true

[dependencies]
quote = "~0.5"
syn = { version = "~0.13", features = ["full"] }
